import streamlit as st

from error_detector import detect_errors
from ai_fixer import auto_fix
from lexer import tokenize

# ---------------- PAGE SETTINGS ----------------

st.set_page_config(
    page_title="AI Compiler Error Fixer",
    page_icon="🤖",
    layout="wide"
)

# ---------------- CUSTOM CSS ----------------

st.markdown("""
<style>

.main {
    background-color: #0f172a;
}

.title {
    text-align: center;
    font-size: 40px;
    font-weight: bold;
    color: #38bdf8;
    margin-bottom: 10px;
}

.subtitle {
    text-align: center;
    color: #cbd5e1;
    margin-bottom: 30px;
}

.stTextArea textarea {
    background-color: #1e293b;
    color: white;
    font-size: 16px;
    border-radius: 10px;
}

.error-box {
    background-color: #7f1d1d;
    padding: 15px;
    border-radius: 10px;
    color: white;
    font-size: 18px;
}

.success-box {
    background-color: #14532d;
    padding: 15px;
    border-radius: 10px;
    color: white;
    font-size: 18px;
}

</style>
""", unsafe_allow_html=True)

# ---------------- TITLE ----------------

st.markdown(
    '<div class="title">🤖 AI-Assisted Compiler Error Fixer</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">Compiler Construction Project using Python + Streamlit</div>',
    unsafe_allow_html=True
)

# ---------------- DEFAULT CODE ----------------

default_code = """for i in range(5)
    print(i

if True
    print("Hello")
"""

# ---------------- INPUT AREA ----------------

code = st.text_area(
    "✍️ Write Your Python Code",
    value=default_code,
    height=300
)

# ---------------- BUTTONS ----------------

col1, col2 = st.columns(2)

with col1:
    check_button = st.button("🔍 Detect Errors")

with col2:
    fix_button = st.button("⚡ Auto Fix Code")

# ---------------- DETECT ERRORS ----------------

if check_button:

    errors = detect_errors(code)

    if errors:

        st.markdown(
            """
            <div class="error-box">
            ❌ <b>Syntax Errors Detected</b>
            </div>
            """,
            unsafe_allow_html=True
        )

        for error in errors:

            st.error(
                f"Line {error['line']}: {error['message']}"
            )

    else:

        st.markdown(
            """
            <div class="success-box">
            ✅ No Syntax Errors Found
            </div>
            """,
            unsafe_allow_html=True
        )

# ---------------- AUTO FIX ----------------

if fix_button:

    fixed_code = auto_fix(code)

    st.subheader("✅ Fixed Code")

    st.code(fixed_code, language="python")

# ---------------- TOKENS ----------------

st.subheader("📌 Tokens Generated by Lexer")

if st.button("Show Tokens"):

    tokens = tokenize(code)

    for token in tokens:
        st.write(token)







